// Verbatim transcription of DESIGN.md § components. Values keep the
// `{table.name}` reference syntax (resolve via resolveTokenRef in
// resolve.ts) rather than pre-resolved literals, so the theme substitution
// rule stays driven from colors.ts alone.

export const components = {
  'button-primary': {
    background: 'colors.electric',
    foreground: 'colors.electric-foreground',
    radius: 'rounded.DEFAULT',
    typography: 'typography.label',
    padding: 'spacing.control-pad-block spacing.control-pad-inline',
    border: 'none',
    minBlockSize: '44px',
  },
  'button-secondary': {
    background: 'transparent',
    foreground: 'colors.foreground',
    borderWidth: 'spacing.rule',
    borderColor: 'colors.border',
    radius: 'rounded.DEFAULT',
    typography: 'typography.label',
    padding: 'spacing.control-pad-block spacing.control-pad-inline',
    minBlockSize: '44px',
  },
  input: {
    background: 'colors.background',
    foreground: 'colors.foreground',
    borderWidth: 'spacing.rule',
    borderColor: 'colors.input',
    radius: 'rounded.DEFAULT',
    typography: 'typography.body',
    padding: 'spacing.control-pad-block spacing.control-pad-inline',
    minBlockSize: '44px',
  },
  radio: {
    radius: 'rounded.full',
    borderWidth: 'spacing.rule',
    borderColor: 'colors.input',
    selectedFill: 'colors.foreground',
    minBlockSize: '44px',
  },
  'focus-ring': {
    outline: '2px solid colors.electric',
    outlineOffset: '2px',
    radius: 'rounded.DEFAULT',
  },
  'focus-ring-on-signal': {
    outline: '2px solid colors.on-signal',
    companion: '2px solid colors.on-signal-companion',
    outlineOffset: '0',
    radius: 'rounded.DEFAULT',
    note: 'Double ring. Required on or adjacent to any signal fill, and wherever an element is flush to a region boundary.',
  },
  'screen-row': {
    borderBlockEndWidth: 'spacing.rule',
    borderBlockEndColor: 'colors.divider',
    padding: 'spacing.row-pad-block spacing.row-pad-inline',
    typography: 'typography.body',
    minBlockSize: '48px',
    hoverBorderColor: 'colors.border',
  },
  'screen-row-alarm': {
    borderBlockStartWidth: 'spacing.rule',
    borderBlockStartColor: 'colors.border',
    borderBlockEndWidth: 'spacing.rule',
    borderBlockEndColor: 'colors.border',
    background: 'colors.background',
  },
  'status-tag-live': {
    background: 'transparent',
    foreground: 'colors.foreground',
    borderWidth: 'spacing.rule',
    borderColor: 'colors.muted-foreground',
    typography: 'typography.label',
    padding: 'spacing.tag-pad-block spacing.tag-pad-inline',
    radius: 'rounded.DEFAULT',
  },
  'status-tag-offline': {
    background: 'colors.alarm',
    foreground: 'colors.alarm-foreground',
    border: 'none',
    typography: 'typography.label',
    padding: 'spacing.tag-pad-block spacing.tag-pad-inline',
    radius: 'rounded.DEFAULT',
  },
  'status-tag-caveat': {
    background: 'colors.amber',
    foreground: 'colors.amber-foreground',
    border: 'none',
    typography: 'typography.label',
    padding: 'spacing.tag-pad-block spacing.tag-pad-inline',
    radius: 'rounded.DEFAULT',
  },
  'banner-alarm': {
    background: 'colors.alarm',
    foreground: 'colors.alarm-foreground',
    linkForeground: 'colors.on-signal',
    linkDecoration: 'underline 2px',
    focus: 'components.focus-ring-on-signal',
    padding: 'spacing.control-pad-block spacing.row-pad-inline',
    radius: 'rounded.DEFAULT',
    typography: 'typography.body-sm',
    inlineSize: 'full-bleed',
    position: 'static flow — never sticky',
  },
  notice: {
    background: 'colors.background',
    foreground: 'colors.foreground',
    borderWidth: 'spacing.rule',
    borderColor: 'colors.border',
    padding: 'spacing.control-pad-block spacing.row-pad-inline',
    radius: 'rounded.DEFAULT',
    typography: 'typography.body-sm',
  },
  'group-header': {
    borderBlockEndWidth: 'spacing.rule',
    borderBlockEndColor: 'colors.border',
    typography: 'typography.label',
    foreground: 'colors.foreground',
    padding: '8px spacing.row-pad-inline',
  },
  'nav-item': {
    background: 'transparent',
    foreground: 'colors.foreground',
    typography: 'typography.body-sm',
    padding: '8px spacing.control-pad-inline',
    radius: 'rounded.DEFAULT',
    minBlockSize: '44px',
  },
  'nav-item-active': {
    background: 'colors.foreground',
    foreground: 'colors.background',
    fontWeight: '800',
  },
  'nav-sheet': {
    background: 'colors.background',
    borderWidth: 'spacing.rule',
    borderColor: 'colors.border',
    radius: 'rounded.DEFAULT',
    inlineSize: 'full-bleed',
    scrim: 'colors.foreground',
    scrimOpacity: '1',
  },
  modal: {
    background: 'colors.background',
    borderWidth: 'spacing.rule',
    borderColor: 'colors.border',
    radius: 'rounded.DEFAULT',
    padding: 'spacing.row-pad-inline',
    scrim: 'colors.foreground',
    scrimOpacity: '1',
  },
  skeleton: {
    background: 'transparent',
    borderBlockEndWidth: 'spacing.rule',
    borderBlockEndColor: 'colors.divider',
    minBlockSize: '48px',
    animation: 'none',
  },
  'storage-meter': {
    trackBorderWidth: 'spacing.rule',
    trackBorderColor: 'colors.border',
    fill: 'colors.foreground',
    blockSize: '8px',
    radius: 'rounded.DEFAULT',
  },
  'upload-progress': {
    trackBorderWidth: 'spacing.rule',
    trackBorderColor: 'colors.border',
    fill: 'colors.foreground',
    blockSize: '4px',
    radius: 'rounded.DEFAULT',
  },
  'media-thumbnail': {
    inlineSize: '64px',
    blockSize: '64px',
    fit: 'cover, square-cropped',
    borderWidth: 'spacing.rule',
    borderColor: 'colors.divider',
    radius: 'rounded.DEFAULT',
  },
  'holding-card-owner': {
    background: 'colors.background',
    foreground: 'colors.foreground',
    borderWidth: 'spacing.rule',
    borderColor: 'colors.border',
    typography: 'typography.player-headline',
    bodyTypography: 'typography.player-body',
  },
  'holding-card-customer': {
    background: 'colors.player-neutral-ground',
    mark: 'colors.player-neutral-mark',
    markSize: '2vmin',
    border: 'none',
    text: 'none — this card carries no text in any language',
  },
  'trial-badge': {
    content: 'wordmark only — never plan, trial, or account wording',
    foreground: '#FFFFFF',
    typography: 'typography.player-label',
    opacity: '0.3',
    maxAreaRatio: '0.02',
    marginZone: 'outer 10% of one corner',
    motion: 'none',
    mirrors: 'by grid alignment, never by insets',
  },
} as const;

export type ComponentName = keyof typeof components;
